/*
  Anonymous Actions
*/
export const AUTHENTICATING_USER = "AUTHENTICATING_USER";
export const AUTHENTICATING_USER_SUCCEDDED = "AUTHENTICATING_USER_SUCCEDDED";
export const AUTHENTICATING_USER_FAILED = "AUTHENTICATING_USER_FAILED";

export const AUTHENTICATING_USER_REQUEST = "AUTHENTICATING_USER_REQUEST";
export const AUTHENTICATING_USER_REQUEST_SUCCEDDED =
  "AUTHENTICATING_USER_REQUEST_SUCCEDDED";
export const AUTHENTICATING_USER_REQUEST_FAILED =
  "AUTHENTICATING_USER_REQUEST_FAILED";


 /*
  Cars Action
 */

  export const FETCHING_CARS = "FETCHING_CARS";
  export const FETCHING_CARS_SUCCEDDED = "FETCHING_CARS_SUCCEDDED";
  export const FETCHING_CARS_FAILED = "FETCHING_CARS_FAILED";
  
  export const SEARCHING_CARS = "SEARCHING_CARS";
  export const SEARCHING_CARS_SUCCEDDED = "SEARCHING_CARS_SUCCEDDED";
  export const SEARCHING_CARS_FAILED = "SEARCHING_CARS_FAILED";  

/*
 user action
*/
export const FETCHING_USER_ACCOUNT_REQUEST = "FETCHING_USER_ACCOUNT_REQUEST"
export const FETCHING_USER_ACCOUNT_SUCCEEDED = "FETCHING_USER_ACCOUNT_SUCCEEDED"
export const FETCHING_USER_ACCOUNT_FAILED = "FETCHING_USER_ACCOUNT_FAILED"
export const FETCHING_USER_PROFILE = "FETCHING_USER_PROFILE"
export const FETCHING_USER_PROFILE_SUCCEEDED = "FETCHING_USER_PROFILE_SUCCEEDED"
export const FETCHING_USER_PROFILE_FAILED = "FETCHING_USER_PROFILE_FAILED"
export const UPDATING_USER_PROFILE = "UPDATING_USER_PROFILE"
