import {
   AUTHENTICATING_USER,
   AUTHENTICATING_USER_FAILED,
   AUTHENTICATING_USER_REQUEST,
   AUTHENTICATING_USER_REQUEST_FAILED,
   AUTHENTICATING_USER_REQUEST_SUCCEDDED,
   AUTHENTICATING_USER_SUCCEDDED,
 } from '../constants/actiontypes'